# Generated by Django 3.2 on 2021-07-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuquan', '0002_enterprise'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='english_name',
            field=models.CharField(default=1, help_text='英文名称', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enterprise',
            name='short_name',
            field=models.CharField(default=1, help_text='简称', max_length=30),
            preserve_default=False,
        ),
    ]
