# Generated by Django 3.2 on 2021-07-01 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yuquan', '0003_auto_20210701_1838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enterprise',
            old_name='content',
            new_name='address',
        ),
    ]
