# Generated by Django 3.2 on 2021-07-06 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yuquan', '0004_rename_content_enterprise_address'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table=None,
        ),
    ]
