# Generated by Django 3.2 on 2021-07-06 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yuquan', '0006_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='yuquan.category'),
        ),
    ]
