# Generated by Django 3.2 on 2021-07-06 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuquan', '0008_cases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cases',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d/', verbose_name='案例'),
        ),
    ]
