# Generated by Django 3.2 on 2021-07-07 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yuquan', '0011_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='short_name',
            new_name='comment',
        ),
    ]
