# Generated by Django 3.2 on 2021-07-08 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuquan', '0012_rename_short_name_customer_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='describe',
            field=models.CharField(default=123, help_text='企业描述', max_length=225),
            preserve_default=False,
        ),
    ]
