# Generated by Django 3.2 on 2021-07-08 08:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('yuquan', '0013_enterprise_describe'),
    ]

    operations = [
        migrations.CreateModel(
            name='service_flow',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('last_mod_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='修改时间')),
                ('title', models.CharField(help_text='名称', max_length=40)),
                ('describe', models.CharField(help_text='描述', max_length=200)),
            ],
            options={
                'verbose_name': '服务流程',
                'db_table': 'service_flow',
            },
        ),
    ]
