# Generated by Django 3.2 on 2021-07-08 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yuquan', '0014_service_flow'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='service_flow',
            new_name='ServiceFlow',
        ),
    ]
