# Generated by Django 3.2 on 2021-07-08 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuquan', '0015_rename_service_flow_serviceflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(default=12, max_length=32, verbose_name='菜单图标'),
            preserve_default=False,
        ),
    ]
