# Generated by Django 3.2 on 2021-07-09 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuquan', '0016_category_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='subtitle',
            field=models.CharField(default='1', max_length=200, verbose_name='副标题'),
            preserve_default=False,
        ),
    ]
