# Generated by Django 3.2 on 2021-07-09 09:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('yuquan', '0017_article_subtitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('last_mod_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='修改时间')),
                ('title', models.CharField(help_text='名称', max_length=40)),
                ('link_url', models.URLField(help_text='网址')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
