# Generated by Django 3.2 on 2021-07-09 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yuquan', '0018_links'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='links',
            options={'verbose_name': '友情链接'},
        ),
        migrations.RenameField(
            model_name='links',
            old_name='title',
            new_name='name',
        ),
        migrations.AlterModelTable(
            name='links',
            table='links',
        ),
    ]
