# Generated by Django 3.2 on 2021-07-12 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuquan', '0019_auto_20210709_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='enterprise_image/%Y%m%d/', verbose_name='企业图片'),
        ),
        migrations.AddField(
            model_name='enterprise',
            name='video_url',
            field=models.FileField(blank=True, null=True, upload_to='enterprise_video/%Y%m%d/', verbose_name='企业视频'),
        ),
    ]
