# Generated by Django 3.2 on 2021-07-12 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuquan', '0020_auto_20210712_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='video_image_url',
            field=models.ImageField(blank=True, null=True, upload_to='enterprise_image/%Y%m%d/', verbose_name='企业视频图片'),
        ),
    ]
