# Generated by Django 3.2 on 2021-07-12 09:41

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('yuquan', '0021_enterprise_video_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='recruit',
            field=mdeditor.fields.MDTextField(default=1, verbose_name='招聘'),
            preserve_default=False,
        ),
    ]
