# Generated by Django 3.2 on 2021-07-12 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuquan', '0022_enterprise_recruit'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='recruit_image_url',
            field=models.ImageField(blank=True, null=True, upload_to='enterprise_image/%Y%m%d/', verbose_name='招聘图片'),
        ),
    ]
