# Generated by Django 3.2 on 2021-07-12 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuquan', '0023_enterprise_recruit_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='video_describe',
            field=models.CharField(default='测试', help_text='视频描述', max_length=225, verbose_name='视频描述'),
            preserve_default=False,
        ),
    ]
