# Generated by Django 3.2 on 2021-07-12 09:56

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('yuquan', '0024_enterprise_video_describe'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='vision',
            field=mdeditor.fields.MDTextField(default='测试', verbose_name='企业愿景'),
            preserve_default=False,
        ),
    ]
