# Generated by Django 3.2 on 2021-07-15 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yuquan', '0025_enterprise_vision'),
    ]

    operations = [
        migrations.AddField(
            model_name='cases',
            name='case_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='yuquan.category'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='photo_url',
            field=models.ImageField(blank=True, null=True, upload_to='photo_image/%Y%m%d/', verbose_name='客户url'),
        ),
    ]
