# Generated by Django 3.2 on 2021-07-15 08:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('yuquan', '0027_cases_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('last_mod_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='修改时间')),
                ('name', models.CharField(help_text='名称', max_length=40)),
                ('image_url', models.ImageField(blank=True, null=True, upload_to='index_image/%Y%m%d/', verbose_name='主页图片')),
            ],
            options={
                'verbose_name': '主页滚动图片',
                'db_table': 'index_image',
            },
        ),
    ]
