# Generated by Django 3.2 on 2021-07-15 09:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('yuquan', '0028_indeximage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('last_mod_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='修改时间')),
                ('name', models.CharField(help_text='名称', max_length=40)),
                ('wechat_url', models.ImageField(blank=True, null=True, upload_to='user_image/%Y%m%d/', verbose_name='微信图片')),
                ('qq_url', models.ImageField(blank=True, null=True, upload_to='user_image/%Y%m%d/', verbose_name='qq图片')),
                ('describe', models.CharField(help_text='描述', max_length=225)),
            ],
            options={
                'verbose_name': '主页滚动图片',
                'db_table': 'users',
            },
        ),
    ]
