# Generated by Django 3.2 on 2021-07-15 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuquan', '0029_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': '员工'},
        ),
        migrations.AddField(
            model_name='enterprise',
            name='beiancode',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='备案号'),
        ),
    ]
