# Generated by Django 3.2 on 2021-07-15 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuquan', '0030_auto_20210715_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterprise',
            name='gongan_beiancode',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='公安备案号'),
        ),
    ]
