# Generated by Django 3.2 on 2021-09-02 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yuquan', '0032_enterprise_beian_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='sort',
            field=models.IntegerField(default=1, help_text='展示顺序', max_length=1),
            preserve_default=False,
        ),
    ]
